### ISSUE TITLE
How to use Utils? 

### ISSUE THREAD

**Issue by moritzbappert** [code-soup/wordpress-plugin-boilerplate#14]
Hey, 
thanks for your great boilerplate, I find it very well structured. I'm just getting set up for building a comprehensive plugin for a client and am customizing some parts of your boilerplate to my needs.

I haven't quite understood how to use the methods of Utils yet, which is defined as trait, which I'm not familiar with. Do you have any code examples for me? 

I want to check 'MIN_PHP_VERSION' from within the Activator Class.

Would be generally great to see your boilerplate in action in some example plugin.

Thanks for your efforts!
Cheers, 
Moritz

**Comment by Bobz-zg** [comment]
Hi, thank you. It's still in beta stage I hope everything is working :)
Anyhow to your question...

traits you use inside of a class, you should refer to documentation: https://www.php.net/manual/en/language.oop5.traits.php
```php
class MyClass {

    use Utils;

    public function __construct() {
        
        // Use as any other method
        $version = $this->get_constant('MIN_WP_VERSION');
    }
}

$myClass = new MyClass;

// Same here, use as any other method
$myClass->get_constant('MIN_WP_VERSION');
```

**Comment by moritzbappert** [comment]
Thanks for your quick reply, @Bobz-zg!

This helps. :)

I'm currently restructuring the boilerplate for myself to use Gulp instead of Webpack as I'm not familiar with the latter yet. Curious to see this develop...

Keep up the nice work!
