### ISSUE TITLE
System Status and Requirements Admin Page

### ISSUE THREAD

**Issue by Bobz-zg** [code-soup/wordpress-plugin-boilerplate#2]
Add system status / requirements page

**Comment by piqusy** [comment]
Ovo bi bilo nešto u stilu: plugin info/about/readme page?

**Comment by Bobz-zg** [comment]
Kao Gravity Forms system status, može identično al bez dodatnih stilova.
Možeš tu pogledat stilove za WP admin, koje klase treba koristit za što: https://github.com/bueltge/wordpress-admin-style

**Comment by piqusy** [comment]
Ovo sve kaj sam dodao je većinom iz Gravity Forms plugina, dorađeno / izbačen višak.
Jedini dodatni stilovi koji su bili potrebni su za Copy System Report container element tak da je styling po defaultu uglavnom.
Trebalo bi još speglat neke stvari i dodati status za dotični plugin

**Comment by Bobz-zg** [comment]
Speglaj
