### ISSUE TITLE
How to use Hooker and Traits?

### ISSUE THREAD

**Issue by digitalbread** [code-soup/wordpress-plugin-boilerplate#38]
How to use Hooker and Traits? The wiki pages for these are blank. Thanks

**Comment by Bobz-zg** [comment]
Ups sorry.
Technically how it works, plugin instance is always available trought global funciton `$myplugin = wppb();`

```php

// Main plugin instance
$instance = wppb();

// Get class which is managing hooks
$hooker = $instance->get_hooker();

// Add action or filter
$hooker->add_action( 'wp_enqueue_scripts', $this, 'enqueue_styles' );

// Or 
$hooker = new WPPB\Hooker();
$myClassInstance = new MyClassForProducts();
$hooker->add_action('which_wordpress_hook_you_use', $myClassInstance, 'method_of_myClassInstance_to_call', 123,3 );


```

**Comment by Bobz-zg** [comment]
1. Using $hooker: https://github.com/code-soup/wordpress-plugin-boilerplate/wiki/07.-Hooking-with-$hooker
2. Using Traits: https://github.com/code-soup/wordpress-plugin-boilerplate/wiki/09.-Using-trait
