### ISSUE TITLE
Love this simple approach! Quick question

### ISSUE THREAD

**Issue by multiplehats** [code-soup/wordpress-plugin-boilerplate#4]
Looking to deploy on wp.org eventually and I need unminified JS and CSS files as well. Have only used Laravel Mix, which makes Webpack easy lol.

Been browsing and trying out a few things but haven't really figured it out yet. How can I use the `config.optimization.js` file to include both `.js` (without compression) and the `.min.js` file?

Appreciate your input!

**Comment by Bobz-zg** [comment]
I have no experience with Laravel Mix, it's hard for me to say how to do it there.
First thing that comes to my mind is to set 2 entry points, minfied and uniminified and run only one trough minifier.

**Comment by multiplehats** [comment]
Thanks for getting back to me so quickly @Bobz-zg 

Would love it if you could give me an idea of how to get this done.

if I remove `-[hash:8]` from `fileName` (not sure how to deal with the hash) it results in 4 files in `./dist`. I get 4 files:
```
admin-8ca50770.js <-- minified (doesn't work)
admin.min-8ca50770.js <-- minified (works)
main-8ca50770.js  <-- not minified
main.min-8ca50770.js <-- minified (works)
```

Here's what I tried and the (only) files I changed:

config-local.js
```
module.exports = {
    entry: {
        main: ["scripts/main.js", "styles/main.scss"],		// root javascript and style files - frontend
        "main.min": ["scripts/main.js", "styles/main.scss"],		// root javascript and style files - frontend
        admin: ["scripts/admin.js", "styles/admin.scss"],	// root javascript and style files - backend
        "admin.min": ["scripts/admin.js", "styles/admin.scss"],	// root javascript and style files - backend
    },
    openBrowserOnWatch: false,				// open browser with devUrl url on watch
    showErrorsInBrowser: true,				// show webpack errors on frontent
    useSSLinDev: false,						// use https: in devUrl
    publicPath: "/wp-content/plugins/woopops",	// path to plugin
    devUrl: "http://mylocal.domain",		// localhost or custom domain name
    proxyUrl: "http://localhost",			// proxyUrl
    proxyPort: 3000,						// port to use on "watch"
    watch: ["includes/**/*.php"],			// folders / files to include in live reload
};
```
config.optimization.js
```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
    noEmitOnErrors: true,
    mangleWasmImports: true,
    removeAvailableModules: true,
    removeEmptyChunks: true,
    mergeDuplicateChunks: true,
    flagIncludedChunks: true,
    occurrenceOrder: true,
    splitChunks: {
        chunks: 'async',
        minSize: 30000,
        maxSize: 0,
        minChunks: 1,
        maxAsyncRequests: 6,
        maxInitialRequests: 4,
        automaticNameDelimiter: '~',
        cacheGroups: {
            defaultVendors: {
                test: /[\\/]node_modules[\\/]/,
                priority: -10,
            },
            default: {
                minChunks: 2,
                priority: -20,
                reuseExistingChunk: true,
            },
        },
    },
    minimize: true,
    minimizer: [
        new TerserPlugin({
            include: /.min\.js(\?.*)?$/i,
            cache: true,
            parallel: true,
            sourceMap: false,
        }),
    ],
};
```
config.js 
```
const path = require("path");
const merge = require("webpack-merge");
const { argv } = require("yargs");

const desire = require("./util/desire");

// Check for local config over
const userConfig = desire(`${__dirname}/../config-local`)
    ? desire(`${__dirname}/../config-local`)
    : desire(`${__dirname}/../config`);

const isProduction = ("production" === argv.mode);
const rootPath = process.cwd();

/**
 * Base config
 */
const config = merge(
    {
        mode: isProduction ? 'production' : 'development',
        copy: "+(icons|audio)/**/*",
        fileName: isProduction ? "[name]-[hash:8]" : "[name]",
        paths: {
            root: rootPath,
            src: path.join(rootPath, "src"),
            path: path.join(rootPath, "dist"),
            publicPath: `/${userConfig.publicPath}/dist/`,
        },
        enabled: {
            watcher: argv.watch,
            production: isProduction,
        },
    },
    userConfig
);

// Export config
module.exports = config;
```

**Comment by Bobz-zg** [comment]
That's good progress.
What you need to do is test to see which entry point are you currently parsing and depending on that apply minification.

**Comment by multiplehats** [comment]
Yeah I think I'm in over my head. Perhaps I should abandon this idea.

**Comment by Bobz-zg** [comment]
Never give up!

I might be able to take a look, but somewhere within next week, not before that.
Why would you need unminified versions?

**Comment by multiplehats** [comment]
Ha! Thanks for inspiring me.

Well, wp.org plugin guidelines state that you need unminified files in your dist directory: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#4-code-must-be-mostly-human-readable

If you download Elementor, you can ses they're doing something similar. 

![image](https://user-images.githubusercontent.com/24393137/102381626-c02bbb80-3fc9-11eb-9a31-6765d3f16690.png)

**Comment by Bobz-zg** [comment]
Hm, well I just checked few of my plugins all of them are minified.
Maybe for initial approval I did submit them readable though, but can't remember that now.

**Comment by multiplehats** [comment]
Thanks @Bobz-zg 

Maybe I'm overthinking this. I'll just submit them compressed and minified and see what happens 👍
