### ISSUE TITLE
`Assets` class failing to locate assets

### ISSUE THREAD

**Issue by varffs** [code-soup/wordpress-plugin-boilerplate#67]
I'm getting 404s for both js and css files on both the frontend and admin. The paths to these files seem to be missing the organisational folder and just looking for the assets in the `/dist` folder e.g. `/dist/admin.js?ver=0.0.1` rather than /dist/scripts/admin.js?ver=0.0.1`

However I note that the `/dist/assets.json` file referenced in L56 of `class-assets.php` does not exist in my dist folder after running both `yarn dev` and `yarn build`. So I'm assuming that the references expected in that file are the cause of the incorrect urls being enqueued.

**Comment by Bobz-zg** [comment]
Another typo, needs to be:
`$this->assets->get('styles/common.css')`
`$this->assets->get('scripts/common.js')`

**Comment by Bobz-zg** [comment]
Oh, ok. Here's the fixed class-assets.php:
https://github.com/code-soup/wordpress-plugin-boilerplate/blob/master/includes/class-assets.php

`assets.json` is generated only when using `yarn build:prod`
